import browser_cookie3
import http.cookiejar
import json
import os


def load_skool_cookies(chrome_profile_path: str, cookies_file: str = None):
    """
    Load skool.com cookies. Returns (cookiejar, cookies_file_path).

    Priority:
      1. cookies.json  - Chrome extension JSON export (auto-detected or via config)
      2. cookies.txt   - Netscape format export (auto-detected or via config)
      3. browser-cookie3 direct Chrome read (may fail on Chrome 127+ App-Bound Encryption)

    cookies_file_path in the return value is a path to a Netscape .txt file for yt-dlp,
    or None if cookies came from browser-cookie3.
    """
    candidates = []

    if cookies_file:
        candidates.append(cookies_file)

    # Auto-detect common filenames in the working directory - prefer .txt, fall back to .json
    candidates += ["cookies.txt", "cookies.json"]

    for path in candidates:
        if not os.path.exists(path):
            continue
        if path.endswith(".json"):
            return _load_from_json(path)
        if path.endswith(".txt"):
            cookiejar = _load_from_cookies_txt(path)
            return cookiejar, os.path.abspath(path)

    # Fall back to browser-cookie3 (may fail on modern Chrome)
    return _load_from_chrome(chrome_profile_path)


def cookies_from_list(cookies: list, txt_path: str):
    """
    Build (cookiejar, netscape_txt_path) from a live cookie list posted by the
    Chrome extension (chrome.cookies.getAll format). Reuses the same JSON->jar
    and Netscape conversion as the file-based export path.
    """
    if not any("skool" in c.get("domain", "") for c in cookies):
        raise RuntimeError("No skool.com cookies in the provided list "
                           "(are you logged into Skool in this browser?).")
    jar = http.cookiejar.CookieJar()
    for c in cookies:
        jar._cookies.setdefault(c["domain"], {}).setdefault(c.get("path", "/"), {})[c["name"]] = (
            _json_to_cookiejar_cookie(c)
        )
    _write_netscape_cookies(cookies, txt_path)
    return jar, txt_path


# ---------------------------------------------------------------------------
# JSON cookie export (Chrome extension format, e.g. "EditThisCookie", "Cookie-Editor")
# ---------------------------------------------------------------------------

def _load_from_json(path: str):
    """
    Load cookies from a Chrome extension JSON export.
    Converts to a requests cookiejar AND writes a Netscape cookies.txt for yt-dlp.
    Returns (cookiejar, netscape_txt_path).
    """
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)

    if not isinstance(data, list):
        raise RuntimeError(
            f"{path} is not a valid cookie JSON export (expected a list of cookie objects)."
        )

    skool_cookies = [c for c in data if "skool" in c.get("domain", "")]
    if not skool_cookies:
        raise RuntimeError(
            f"No skool.com cookies found in {path}.\n"
            "Make sure you exported cookies while logged into Skool."
        )

    # Build requests cookiejar
    jar = http.cookiejar.CookieJar()
    for c in data:
        jar._cookies.setdefault(c["domain"], {}).setdefault(c["path"], {})[c["name"]] = (
            _json_to_cookiejar_cookie(c)
        )

    # Write Netscape cookies.txt for yt-dlp
    txt_path = os.path.splitext(os.path.abspath(path))[0] + "_netscape.txt"
    _write_netscape_cookies(data, txt_path)

    return jar, txt_path


def _json_to_cookiejar_cookie(c: dict):
    """Convert a JSON cookie dict to an http.cookiejar.Cookie."""
    expires = int(c.get("expirationDate", 0)) if not c.get("session") else None
    domain = c["domain"]
    domain_initial_dot = domain.startswith(".")

    return http.cookiejar.Cookie(
        version=0,
        name=c["name"],
        value=c["value"],
        port=None,
        port_specified=False,
        domain=domain,
        domain_specified=True,
        domain_initial_dot=domain_initial_dot,
        path=c.get("path", "/"),
        path_specified=True,
        secure=c.get("secure", False),
        expires=expires,
        discard=c.get("session", False),
        comment=None,
        comment_url=None,
        rest={"HttpOnly": ""} if c.get("httpOnly") else {},
    )


def _write_netscape_cookies(cookies: list, output_path: str):
    """Write cookies list to Netscape/Mozilla format for yt-dlp --cookies."""
    lines = ["# Netscape HTTP Cookie File", "# Generated by skool-downloader\n"]
    for c in cookies:
        domain = c["domain"]
        include_subdomains = "TRUE" if not c.get("hostOnly", True) else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure", False) else "FALSE"
        expires = int(c.get("expirationDate", 0)) if not c.get("session") else "0"
        name = c["name"]
        value = c["value"]
        lines.append(f"{domain}\t{include_subdomains}\t{path}\t{secure}\t{expires}\t{name}\t{value}")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


# ---------------------------------------------------------------------------
# Netscape cookies.txt
# ---------------------------------------------------------------------------

def _load_from_cookies_txt(path: str):
    """Load a Netscape-format cookies.txt file into a requests-compatible cookiejar."""
    jar = http.cookiejar.MozillaCookieJar(path)
    try:
        jar.load(ignore_discard=True, ignore_expires=True)
    except Exception as e:
        raise RuntimeError(
            f"Failed to load cookies from {path}: {e}\n"
            "Make sure the file is in Netscape/Mozilla cookies.txt format."
        )
    skool_cookies = [c for c in jar if "skool" in c.domain]
    if not skool_cookies:
        raise RuntimeError(
            f"No skool.com cookies found in {path}.\n"
            "Make sure you exported cookies while logged into Skool."
        )
    return jar


# ---------------------------------------------------------------------------
# browser-cookie3 (Chrome direct read)
# ---------------------------------------------------------------------------

def _load_from_chrome(chrome_profile_path: str):
    """Attempt to read cookies directly from Chrome via browser-cookie3."""
    cookie_file = os.path.join(chrome_profile_path, "Network", "Cookies")
    if not os.path.exists(cookie_file):
        cookie_file = os.path.join(chrome_profile_path, "Cookies")

    if not os.path.exists(cookie_file):
        raise RuntimeError(
            f"No cookies source found. Checked:\n"
            f"  {os.path.join(chrome_profile_path, 'Network', 'Cookies')}\n"
            f"  {os.path.join(chrome_profile_path, 'Cookies')}\n"
            f"  cookies.json (not found in project folder)\n"
            f"  cookies.txt  (not found in project folder)\n\n"
            + _export_instructions()
        )

    try:
        cookiejar = browser_cookie3.chrome(
            domain_name=".skool.com",
            cookie_file=cookie_file
        )
        cookies_list = list(cookiejar)
        if not cookies_list:
            raise RuntimeError(
                "No skool.com cookies found in the Chrome profile.\n"
                "Make sure you are logged into Skool in Chrome Profile 7.\n\n"
                + _export_instructions()
            )
        return cookiejar, None

    except PermissionError:
        raise RuntimeError(
            "Could not read Chrome's Cookies file - it may be locked.\n"
            "Close Chrome completely and try again, or use the export method below.\n\n"
            + _export_instructions()
        )
    except RuntimeError:
        raise
    except Exception as e:
        raise RuntimeError(
            f"browser-cookie3 failed: {e}\n"
            "Chrome 127+ uses App-Bound Encryption that blocks direct cookie reads.\n\n"
            + _export_instructions()
        )


def _export_instructions() -> str:
    return (
        "--- Export cookies manually ---\n"
        "1. Install 'Cookie-Editor' or 'EditThisCookie' in Chrome\n"
        "2. Log into Skool in Chrome Profile 7\n"
        "3. Visit https://www.skool.com and open the extension\n"
        "4. Export as JSON and save as 'cookies.json' in this project folder\n"
        "5. Run python main.py again"
    )
